"""add analysis_status to journal_entries

Revision ID: 12bad50979a5
Revises: b2f4a1c9d3e7
Create Date: 2026-05-29 15:46:42.266043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bad50979a5'
down_revision: Union[str, None] = 'b2f4a1c9d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('analysis_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'analysis_status')
    # ### end Alembic commands ###
