"""add positive_patterns and acute_risk_detected

Revision ID: 2cf1d37e705e
Revises: 7d97d69bf17d
Create Date: 2026-05-29 17:37:41.895060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf1d37e705e'
down_revision: Union[str, None] = '7d97d69bf17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('positive_patterns', sa.JSON(), nullable=True))
    op.add_column('journal_entries', sa.Column('acute_risk_detected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'acute_risk_detected')
    op.drop_column('journal_entries', 'positive_patterns')
    # ### end Alembic commands ###
