"""add recommended_exercises to journal_entries

Revision ID: 7d97d69bf17d
Revises: 12bad50979a5
Create Date: 2026-05-29 15:58:14.616734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d97d69bf17d'
down_revision: Union[str, None] = '12bad50979a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('recommended_exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'recommended_exercises')
    # ### end Alembic commands ###
